# Generated by Django 5.0.6 on 2024-07-11 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nomcategoria', models.CharField(max_length=255)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('numdoc', models.CharField(max_length=25)),
                ('razonsocial', models.CharField(max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CodigoCorreo',
            fields=[
                ('id_codigo_correo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=45, null=True)),
                ('correo', models.CharField(blank=True, max_length=80, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'codigo_correo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('idcompradetalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.FloatField()),
            ],
            options={
                'db_table': 'compra_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('idcompra', models.AutoField(primary_key=True, serialize=False)),
                ('numcorrelativo', models.CharField(max_length=11)),
                ('fechacompra', models.DateField()),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('iddepartamentos', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombredepartamento', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'departamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallecategoriaxunidades',
            fields=[
                ('iddetallecategoriaxunidades', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detallecategoriaxunidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalletipousuarioxmodulos',
            fields=[
                ('iddetalletipousuarioxmodulos', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detalletipousuarioxmodulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Distritos',
            fields=[
                ('iddistrito', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombredistrito', models.CharField(max_length=255)),
                ('ubigeo', models.CharField(blank=True, max_length=255, null=True)),
                ('checked', models.IntegerField()),
            ],
            options={
                'db_table': 'distritos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idempresa', models.AutoField(primary_key=True, serialize=False)),
                ('ruc', models.CharField(max_length=11)),
                ('razonsocial', models.CharField(max_length=255)),
                ('nombrecomercial', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('mododev', models.IntegerField()),
                ('logo', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=25)),
                ('usersec', models.CharField(max_length=255)),
                ('passwordsec', models.CharField(max_length=255)),
                ('ubigueo', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lotes',
            fields=[
                ('idLote', models.AutoField(primary_key=True, serialize=False)),
                ('identificador', models.CharField(max_length=50)),
                ('fecha_produccion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'lotes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modopago',
            fields=[
                ('idmodoPago', models.AutoField(primary_key=True, serialize=False)),
                ('modo_pago', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'modopago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('idmodulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombremodulo', models.CharField(max_length=255)),
                ('estado', models.IntegerField()),
                ('url', models.CharField(max_length=45)),
                ('logo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'modulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Numserie',
            fields=[
                ('idnumserie', models.AutoField(primary_key=True, serialize=False)),
                ('numserie', models.CharField(blank=True, max_length=4, null=True)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'numserie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nomproducto', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('precioCompra', models.FloatField()),
                ('preciounitario', models.FloatField()),
                ('stockactual', models.IntegerField()),
                ('imagenprod', models.CharField(max_length=255)),
                ('estado', models.IntegerField()),
                ('codigo', models.CharField(max_length=45)),
                ('codigo_barras', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('idproveedor', models.AutoField(primary_key=True, serialize=False)),
                ('numdoc', models.CharField(max_length=255)),
                ('razonsocial', models.CharField(max_length=255)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('idprovincia', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombreprovincia', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'provincias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipocliente',
            fields=[
                ('idtipocliente', models.AutoField(primary_key=True, serialize=False)),
                ('nomtipocliente', models.CharField(max_length=255)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'tipocliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipodocumento',
            fields=[
                ('idtipodocumento', models.AutoField(primary_key=True, serialize=False)),
                ('codigosunat', models.CharField(max_length=10)),
                ('nombredocumento', models.CharField(max_length=255)),
                ('abrrdoc', models.CharField(max_length=10)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'tipodocumento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEntidad',
            fields=[
                ('id_tipo_entidad', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_entidad', models.CharField(blank=True, max_length=45, null=True)),
                ('codigo', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('abreviatura', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tipo_entidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoIgv',
            fields=[
                ('id_tipo_igv', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('tipo_igv', models.CharField(max_length=60)),
                ('codigo_de_tributo', models.IntegerField()),
            ],
            options={
                'db_table': 'tipo_igvs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipousuario',
            fields=[
                ('idtipousuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombretipousuario', models.CharField(max_length=255)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'tipousuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('idunidad', models.AutoField(primary_key=True, serialize=False)),
                ('codigounidad', models.CharField(max_length=255)),
                ('abrunidad', models.CharField(max_length=255)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'unidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecompleto', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=10)),
                ('dni', models.CharField(max_length=10)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idventa', models.AutoField(primary_key=True, serialize=False)),
                ('numcorrelativo', models.CharField(max_length=10)),
                ('fechaemision', models.DateField()),
                ('horaemision', models.TimeField()),
                ('estado', models.IntegerField()),
                ('ruta_pdf', models.CharField(max_length=500)),
                ('ruta_cdr', models.CharField(max_length=500)),
                ('respuesta_sunat_descripcion', models.CharField(max_length=500)),
                ('respuesta_sunat_codigo', models.CharField(max_length=500)),
                ('total_gravada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_igv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_gratuita', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_exonerada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_inafecta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_a_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('idventadetalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('preciosubtotal', models.FloatField()),
            ],
            options={
                'db_table': 'venta_detalle',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='SubirDocumentoImagen',
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='software.empresa')),
                ('idempresa', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=75, null=True)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('direccion', models.CharField(blank=True, max_length=75, null=True)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
    ]



