# Generated by Django 5.2.6 on 2026-04-09 18:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0008_alter_proveedor_numdoc_sin_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaVentas',
            fields=[
                ('idauditoria_venta', models.AutoField(primary_key=True, serialize=False)),
                ('idventa', models.IntegerField()),
                ('accion', models.CharField(max_length=20)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('fecha_auditoria', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auditoría de Venta',
                'verbose_name_plural': 'Auditorías de Ventas',
                'db_table': 'auditoria_ventas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistorialImposicion',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'historial_imposicion',
                'ordering': ['-fecha_cambio'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ImposicionPlaca',
            fields=[
                ('id_imposicion', models.AutoField(primary_key=True, serialize=False)),
                ('numero_placa', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_placa', models.CharField(choices=[('nueva', 'Placa Nueva'), ('transferencia', 'Transferencia'), ('duplicado', 'Duplicado')], default='nueva', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_tramite', models.DateField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento_tramite', models.DateField(blank=True, null=True)),
                ('costo_tramite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_placa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('otros_costos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tiene_tarjeta_propiedad', models.BooleanField(default=False)),
                ('tiene_soat', models.BooleanField(default=False)),
                ('tiene_revision_tecnica', models.BooleanField(default=False)),
                ('numero_expediente', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_tramite', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_tramite', 'En Trámite'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField(default=1)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Imposición de Placa',
                'verbose_name_plural': 'Imposiciones de Placas',
                'db_table': 'imposicion_placas',
                'ordering': ['-fecha_solicitud'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReaperturaCaja',
            fields=[
                ('id_reapertura', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha_reapertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre_reapertura', models.DateTimeField(blank=True, null=True)),
                ('codigo_2fa_enviado', models.CharField(blank=True, max_length=6, null=True)),
                ('estado', models.CharField(choices=[('reabierta', 'Reabierta'), ('cerrada_nuevamente', 'Cerrada Nuevamente')], default='reabierta', max_length=20)),
            ],
            options={
                'db_table': 'reapertura_caja',
                'ordering': ['-fecha_reapertura'],
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Detallecategoriaxunidades',
        ),
        migrations.AlterModelOptions(
            name='seriecomprobante',
            options={'managed': True, 'ordering': ['idtipocomprobante__codigo', 'serie'], 'verbose_name': 'Serie de Comprobante', 'verbose_name_plural': 'Series de Comprobante'},
        ),
        migrations.AlterModelOptions(
            name='tipocomprobante',
            options={'managed': True, 'ordering': ['codigo'], 'verbose_name': 'Tipo de Comprobante', 'verbose_name_plural': 'Tipos de Comprobante'},
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='producto',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='codigo_barras',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precioCompra',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='preciounitario',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stockactual',
        ),
        migrations.RemoveField(
            model_name='unidades',
            name='codigounidad',
        ),
        migrations.RemoveField(
            model_name='ventadetalle',
            name='preciosubtotal',
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='id_repuesto_comprado',
            field=models.ForeignKey(blank=True, db_column='id_repuesto_comprado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='compradetalle', to='software.repuestocomp'),
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='id_vehiculo',
            field=models.ForeignKey(blank=True, db_column='id_vehiculo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='compradetalle', to='software.vehiculo'),
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='idcompra',
            field=models.ForeignKey(blank=True, db_column='idcompra', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='compradetalle', to='software.compras'),
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='compras',
            name='id_almacen',
            field=models.ForeignKey(blank=True, db_column='id_almacen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='software.almacenes'),
        ),
        migrations.AddField(
            model_name='compras',
            name='id_forma_pago',
            field=models.ForeignKey(blank=True, db_column='id_forma_pago', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='compras', to='software.formapago'),
        ),
        migrations.AddField(
            model_name='compras',
            name='id_sucursal',
            field=models.ForeignKey(blank=True, db_column='id_sucursal', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='compras', to='software.sucursales'),
        ),
        migrations.AddField(
            model_name='compras',
            name='id_tipo_pago',
            field=models.ForeignKey(blank=True, db_column='id_tipo_pago', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='compras', to='software.tipopago'),
        ),
        migrations.AddField(
            model_name='compras',
            name='idproveedor',
            field=models.ForeignKey(blank=True, db_column='idproveedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='compras', to='software.proveedor'),
        ),
        migrations.AddField(
            model_name='compras',
            name='idtipocliente',
            field=models.ForeignKey(blank=True, db_column='idtipocliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='compras', to='software.tipocliente'),
        ),
        migrations.AddField(
            model_name='compras',
            name='total_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='detalletipousuarioxmodulos',
            name='idmodulo',
            field=models.ForeignKey(blank=True, db_column='idmodulo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='software.modulos'),
        ),
        migrations.AddField(
            model_name='detalletipousuarioxmodulos',
            name='idtipousuario',
            field=models.ForeignKey(blank=True, db_column='idtipousuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='software.tipousuario'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='empresa',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si la empresa está activa en el sistema', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='afectacion_sunat',
            field=models.IntegerField(default=20, help_text='Código de afectación tributaria general', verbose_name='Afectación General SUNAT'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='icbper',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Impuesto al Consumo de Bolsas Plásticas', max_digits=5, verbose_name='ICBPER'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='igv',
            field=models.DecimalField(decimal_places=2, default=18.0, help_text='Porcentaje de IGV aplicable', max_digits=5, verbose_name='IGV (%)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='isc',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Impuesto Selectivo al Consumo', max_digits=5, verbose_name='ISC (%)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pagina',
            field=models.CharField(blank=True, help_text='Pagina web de la empresa', max_length=255, null=True, verbose_name='Pagina'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='publicidad',
            field=models.TextField(blank=True, help_text='Descripción de actividades o mensaje publicitario', null=True, verbose_name='Publicidad'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='slogan',
            field=models.CharField(blank=True, help_text='Slogan o frase promocional de la empresa', max_length=255, null=True, verbose_name='Slogan'),
        ),
        migrations.AddField(
            model_name='modulos',
            name='idmodulo_padre',
            field=models.ForeignKey(blank=True, db_column='idmodulo_padre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='submodulos', to='software.modulos'),
        ),
        migrations.AddField(
            model_name='modulos',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='id_movimiento',
            field=models.ForeignKey(blank=True, db_column='id_movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='software.aperturacierrecaja'),
        ),
        migrations.AddField(
            model_name='producto',
            name='idcategoria',
            field=models.ForeignKey(db_column='idcategoria', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='productos', to='software.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='idcilindrada',
            field=models.ForeignKey(db_column='idcilindrada', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='productos', to='software.cilindrada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='idcolor',
            field=models.ForeignKey(db_column='idcolor', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='productos', to='software.color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='idmarca',
            field=models.ForeignKey(db_column='idmarca', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='productos', to='software.marca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='idunidad',
            field=models.ForeignKey(db_column='idunidad', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='productos', to='software.unidades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provincia',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='region',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='codigo_interno',
            field=models.CharField(blank=True, db_column='codigo_interno', max_length=50, null=True, verbose_name='Código Interno'),
        ),
        migrations.AddField(
            model_name='repuestocomp',
            name='modelo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='idcompradetalle',
            field=models.ForeignKey(blank=True, db_column='idcompradetalle', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='software.compradetalle'),
        ),
        migrations.AddField(
            model_name='tipoentidad',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tipoigv',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='unidades',
            name='codigo_sunat',
            field=models.CharField(default=1, max_length=10, verbose_name='Código SUNAT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='es_dueno',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_sucursal',
            field=models.ForeignKey(blank=True, db_column='id_sucursal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='software.sucursales'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='idempresa',
            field=models.ForeignKey(blank=True, db_column='idempresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='software.empresa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='idtipousuario',
            field=models.ForeignKey(db_column='idtipousuario', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='software.tipousuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='anio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='ganancia',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='id_repuesto_comprado',
            field=models.ForeignKey(blank=True, db_column='id_repuesto_comprado', null=True, on_delete=django.db.models.deletion.CASCADE, to='software.repuestocomp'),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='id_vehiculo',
            field=models.ForeignKey(blank=True, db_column='id_vehiculo', null=True, on_delete=django.db.models.deletion.CASCADE, to='software.vehiculo'),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='idventa',
            field=models.ForeignKey(db_column='idventa', default=1, on_delete=django.db.models.deletion.CASCADE, to='software.ventas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='precio_venta_contado',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='precio_venta_credito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='tipo_item',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventas',
            name='sunat_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='sunat_estado',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='sunat_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='sunat_pdf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='sunat_xml',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aperturacierrecaja',
            name='fecha_apertura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='caja',
            name='id_sucursal',
            field=models.ForeignKey(db_column='id_sucursal', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='software.sucursales'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caja',
            name='nombre_caja',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caja',
            name='numero_caja',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numdoc',
            field=models.CharField(max_length=25, unique=True, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='subtotal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='compras',
            name='estado',
            field=models.IntegerField(db_column='estado', default=1),
        ),
        migrations.AlterField(
            model_name='compras',
            name='fechacompra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compras',
            name='numcorrelativo',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(help_text='Dirección fiscal de la empresa', max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='idempresa',
            field=models.AutoField(db_column='idempresa', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.CharField(blank=True, help_text='Ruta del archivo de logo de la empresa', max_length=255, null=True, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='mododev',
            field=models.IntegerField(choices=[(0, 'Desarrollo'), (1, 'Producción')], default=0, help_text='0: Desarrollo, 1: Producción', verbose_name='Modo de Operación'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombrecomercial',
            field=models.CharField(help_text='Nombre comercial de la empresa', max_length=255, verbose_name='Nombre Comercial'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='passwordsec',
            field=models.CharField(blank=True, help_text='Clave de seguridad para servicios SUNAT', max_length=255, null=True, verbose_name='Clave SUNAT'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razonsocial',
            field=models.CharField(help_text='Razón social de la empresa', max_length=255, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ruc',
            field=models.CharField(help_text='Registro Único de Contribuyentes (11 dígitos)', max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11, message='El RUC debe tener 11 dígitos'), django.core.validators.MaxLengthValidator(11, message='El RUC debe tener 11 dígitos'), django.core.validators.RegexValidator(message='El RUC debe contener solo números', regex='^\\d{11}$')], verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono de contacto', max_length=25, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ubigueo',
            field=models.CharField(blank=True, help_text='Código de ubicación geográfica (ubigeo)', max_length=10, null=True, verbose_name='Ubigeo'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='usersec',
            field=models.CharField(blank=True, help_text='Usuario para acceso a servicios SUNAT', max_length=255, null=True, verbose_name='Usuario SUNAT'),
        ),
        migrations.AlterField(
            model_name='modulos',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='modulos',
            name='logo',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='modulos',
            name='url',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.IntegerField(db_column='estado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idproducto',
            field=models.AutoField(db_column='idproducto', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagenprod',
            field=models.CharField(db_column='imagenprod', max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nomproducto',
            field=models.CharField(db_column='nomproducto', max_length=255),
        ),
        migrations.AlterField(
            model_name='seriecomprobante',
            name='estado',
            field=models.IntegerField(default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='seriecomprobante',
            name='idtipocomprobante',
            field=models.ForeignKey(db_column='idtipocomprobante', on_delete=django.db.models.deletion.CASCADE, related_name='seriecomprobante', to='software.tipocomprobante', verbose_name='Tipo de Comprobante'),
        ),
        migrations.AlterField(
            model_name='seriecomprobante',
            name='numero_actual',
            field=models.IntegerField(default=0, help_text='Número correlativo actual del comprobante (inicia en 0)', verbose_name='Número Actual'),
        ),
        migrations.AlterField(
            model_name='seriecomprobante',
            name='serie',
            field=models.CharField(help_text='Serie del comprobante (4 caracteres alfanuméricos)', max_length=4, validators=[django.core.validators.RegexValidator(message='La serie debe tener exactamente 4 caracteres alfanuméricos en mayúsculas', regex='^[A-Z0-9]{4}$')], verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='sucursales',
            name='estado',
            field=models.IntegerField(db_column='estado', default=1),
        ),
        migrations.AlterField(
            model_name='tipocliente',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tipocomprobante',
            name='abreviatura',
            field=models.CharField(help_text='Abreviatura del tipo de comprobante (ej: FACT, BOL)', max_length=50, verbose_name='Abreviatura'),
        ),
        migrations.AlterField(
            model_name='tipocomprobante',
            name='codigo',
            field=models.CharField(help_text='Código del tipo de comprobante (ej: 01, 03, 07). Único entre registros activos.', max_length=10, validators=[django.core.validators.RegexValidator(message='El código solo puede contener números, letras mayúsculas y guiones', regex='^[0-9A-Z\\-]+$')], verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tipocomprobante',
            name='estado',
            field=models.IntegerField(default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='tipocomprobante',
            name='nombre',
            field=models.CharField(help_text='Nombre completo del tipo de comprobante', max_length=255, verbose_name='Nombre del Comprobante'),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='abrunidad',
            field=models.CharField(max_length=255, verbose_name='Nombre de la unidad'),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='estado',
            field=models.BooleanField(default=False, help_text='Indica si la unidad está activa (True) o desactivada (False)', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='seriecomprobante',
            unique_together={('idtipocomprobante', 'serie')},
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nomproducto'], name='producto_nomprod_970239_idx'),
        ),
        migrations.AlterModelTable(
            name='ventadetalle',
            table='ventadetalle',
        ),
        migrations.AddField(
            model_name='auditoriaventas',
            name='idusuario',
            field=models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.DO_NOTHING, to='software.usuario'),
        ),
        migrations.AddField(
            model_name='historialimposicion',
            name='idusuario',
            field=models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to='software.usuario'),
        ),
        migrations.AddField(
            model_name='imposicionplaca',
            name='id_sucursal',
            field=models.ForeignKey(blank=True, db_column='id_sucursal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='software.sucursales'),
        ),
        migrations.AddField(
            model_name='imposicionplaca',
            name='id_vehiculo',
            field=models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.CASCADE, related_name='imposiciones_placa', to='software.vehiculo'),
        ),
        migrations.AddField(
            model_name='imposicionplaca',
            name='idcliente',
            field=models.ForeignKey(db_column='idcliente', on_delete=django.db.models.deletion.CASCADE, related_name='imposiciones_placa', to='software.cliente'),
        ),
        migrations.AddField(
            model_name='imposicionplaca',
            name='idusuario',
            field=models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, related_name='imposiciones_registradas', to='software.usuario'),
        ),
        migrations.AddField(
            model_name='imposicionplaca',
            name='idventa',
            field=models.ForeignKey(db_column='idventa', on_delete=django.db.models.deletion.CASCADE, related_name='imposiciones_placa', to='software.ventas'),
        ),
        migrations.AddField(
            model_name='historialimposicion',
            name='id_imposicion',
            field=models.ForeignKey(db_column='id_imposicion', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='software.imposicionplaca'),
        ),
        migrations.AddField(
            model_name='reaperturacaja',
            name='id_movimiento',
            field=models.ForeignKey(db_column='id_movimiento', on_delete=django.db.models.deletion.CASCADE, related_name='reaperturas', to='software.aperturacierrecaja'),
        ),
        migrations.AddField(
            model_name='reaperturacaja',
            name='usuario_solicitante',
            field=models.ForeignKey(blank=True, db_column='usuario_solicitante', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reaperturas_solicitadas', to='software.usuario'),
        ),
    ]
