# Generated by Django 5.2.6 on 2026-04-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0009_auditoriaventas_historialimposicion_imposicionplaca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalle',
            name='precio_venta_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
