# Generated by Django 5.2.6 on 2026-04-15 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0010_producto_codigo_interno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='idcompra',
            field=models.ForeignKey(blank=True, db_column='idcompra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='software.compras'),
        ),
    ]
