# Generated by Django 5.2.6 on 2026-04-18 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0011_movimientocaja_idcompra_producto_codigo_interno'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='credito',
            name='es_directo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credito',
            name='id_almacen',
            field=models.ForeignKey(blank=True, db_column='id_almacen', null=True, on_delete=django.db.models.deletion.SET_NULL, to='software.almacenes'),
        ),
        migrations.AddField(
            model_name='credito',
            name='id_repuesto_comprado',
            field=models.ForeignKey(blank=True, db_column='id_repuesto_comprado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='software.repuestocomp'),
        ),
        migrations.AddField(
            model_name='credito',
            name='id_sucursal',
            field=models.ForeignKey(blank=True, db_column='id_sucursal', null=True, on_delete=django.db.models.deletion.SET_NULL, to='software.sucursales'),
        ),
        migrations.AddField(
            model_name='credito',
            name='id_vehiculo',
            field=models.ForeignKey(blank=True, db_column='id_vehiculo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='software.vehiculo'),
        ),
        migrations.AddField(
            model_name='credito',
            name='idcliente',
            field=models.ForeignKey(blank=True, db_column='idcliente', null=True, on_delete=django.db.models.deletion.CASCADE, to='software.cliente'),
        ),
        migrations.AddField(
            model_name='credito',
            name='idusuario',
            field=models.ForeignKey(blank=True, db_column='idusuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='software.usuario'),
        ),
        migrations.AddField(
            model_name='credito',
            name='tipo_item',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cuotasventa',
            name='idcredito',
            field=models.ForeignKey(blank=True, db_column='idcredito', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='software.credito'),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_interno',
            field=models.CharField(blank=True, db_column='codigo_interno', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='credito',
            name='idventa',
            field=models.OneToOneField(blank=True, db_column='idventa', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credito', to='software.ventas'),
        ),
        migrations.AlterField(
            model_name='cuotasventa',
            name='idventa',
            field=models.ForeignKey(blank=True, db_column='idventa', null=True, on_delete=django.db.models.deletion.CASCADE, to='software.ventas'),
        ),
    ]
