# Generated by Django 5.2.6 on 2026-04-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0012_credito_cantidad_credito_es_directo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='estado_pago',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='cuota',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuota',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cuota',
            name='saldo_cuota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
