# Generated by Django 5.2.6 on 2026-04-21 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0013_cuota_estado_pago_cuota_fecha_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoCuotaCompra',
            fields=[
                ('idpagocuotacompra', models.AutoField(primary_key=True, serialize=False)),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('numero_operacion', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField(default=1)),
                ('id_tipo_pago', models.ForeignKey(db_column='id_tipo_pago', on_delete=django.db.models.deletion.CASCADE, to='software.tipopago')),
                ('idcuota', models.ForeignKey(db_column='idcuota', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='software.cuota')),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to='software.usuario')),
            ],
            options={
                'db_table': 'pagos_cuota_compra',
                'ordering': ['-fecha_pago'],
                'managed': True,
            },
        ),
    ]
