# Generated by Django 5.2.6 on 2026-04-21 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0014_pagocuotacompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocuota',
            name='id_movimiento_caja',
            field=models.ForeignKey(blank=True, db_column='id_movimiento_caja', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_cuota', to='software.movimientocaja'),
        ),
    ]
