# Generated by Django 5.2.6 on 2026-04-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0015_pagocuota_id_movimiento_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='notificaciones_sonido',
            field=models.BooleanField(default=True),
        ),
    ]
