# Generated by Django 5.2.6 on 2026-04-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0016_usuario_notificaciones_sonido'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sonido_notificacion',
            field=models.FileField(blank=True, null=True, upload_to='notificaciones/sonidos/'),
        ),
    ]
