# Generated by Django 5.2.6 on 2026-04-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0017_usuario_sonido_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/perfiles/'),
        ),
    ]
