# Generated by Django 5.2.6 on 2026-04-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0018_usuario_imagen_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='costo_reparacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='credito',
            name='dias_gracia',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='credito',
            name='fecha_retencion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credito',
            name='margen_recuperacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
