# Generated by Django 5.2.6 on 2026-04-26 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0019_credito_costo_reparacion_credito_dias_gracia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreCredito',
            fields=[
                ('id_pre_credito', models.AutoField(primary_key=True, serialize=False)),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Inicial (Adelanto)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('id_sucursal', models.ForeignKey(blank=True, db_column='id_sucursal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_creditos', to='software.sucursales', verbose_name='Sucursal')),
                ('id_vehiculo', models.ForeignKey(blank=True, db_column='id_vehiculo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_creditos', to='software.vehiculo', verbose_name='Vehículo')),
                ('idcliente', models.ForeignKey(db_column='idcliente', on_delete=django.db.models.deletion.CASCADE, related_name='pre_creditos', to='software.cliente', verbose_name='Cliente')),
                ('idusuario', models.ForeignKey(blank=True, db_column='idusuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_creditos', to='software.usuario', verbose_name='Usuario Registrador')),
            ],
            options={
                'verbose_name': 'Pre-Crédito',
                'verbose_name_plural': 'Pre-Créditos',
                'db_table': 'pre_creditos',
                'ordering': ['-fecha_registro'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallePagoInicial',
            fields=[
                ('id_detalle_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('id_tipo_pago', models.ForeignKey(blank=True, db_column='id_tipo_pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_pago_inicial', to='software.tipopago', verbose_name='Método de Pago')),
                ('id_pre_credito', models.ForeignKey(db_column='id_pre_credito', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pago', to='software.precredito', verbose_name='Pre-Crédito')),
            ],
            options={
                'verbose_name': 'Detalle de Pago Inicial',
                'verbose_name_plural': 'Detalles de Pago Inicial',
                'db_table': 'detalle_pago_inicial',
                'managed': True,
            },
        ),
    ]
