# Generated by Django 5.2.6 on 2026-04-26 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0020_pre_financiamiento_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('idmodelo', models.AutoField(db_column='idmodelo', primary_key=True, serialize=False)),
                ('nombremodelo', models.CharField(db_column='nombremodelo', max_length=100)),
                ('estado', models.IntegerField(db_column='estado', default=1)),
            ],
            options={
                'db_table': 'modelo',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='idmodelo',
            field=models.ForeignKey(blank=True, db_column='idmodelo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='productos', to='software.modelo'),
        ),
    ]
