# Generated by Django 5.2.6 on 2026-04-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0021_modelo_producto_idmodelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepagoinicial',
            name='numero_operacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Operación'),
        ),
        migrations.AlterField(
            model_name='precredito',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('completado', 'Completado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
