# Generated by Django 5.2.6 on 2026-04-27 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0022_detallepagoinicial_numero_operacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garante',
            fields=[
                ('id_garante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('numdoc', models.CharField(max_length=20, verbose_name='Número de Documento (DNI)')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('estado', models.IntegerField(default=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Garante',
                'verbose_name_plural': 'Garantes',
                'db_table': 'garantes',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='conyuge_direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección del Cónyuge'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='conyuge_dni',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI del Cónyuge'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='conyuge_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Cónyuge'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='dni_gerente',
            field=models.CharField(blank=True, help_text='DNI del representante legal', max_length=20, null=True, verbose_name='DNI Gerente'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='gerente_general',
            field=models.CharField(blank=True, help_text='Nombre completo del representante legal', max_length=255, null=True, verbose_name='Gerente General'),
        ),
        migrations.AddField(
            model_name='credito',
            name='id_garante',
            field=models.ForeignKey(blank=True, db_column='id_garante', null=True, on_delete=django.db.models.deletion.SET_NULL, to='software.garante'),
        ),
    ]
