# Generated by Django 5.2.6 on 2026-04-29 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0023_garante_cliente_conyuge_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garante',
            name='idcliente',
            field=models.ForeignKey(blank=True, db_column='idcliente', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garantes', to='software.cliente', verbose_name='Cliente'),
        ),
    ]
