# Generated by Django 5.2.6 on 2026-04-29 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0024_garante_idcliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituacionVehiculo',
            fields=[
                ('id_situacion', models.AutoField(db_column='id_situacion', primary_key=True, serialize=False)),
                ('nombre_situacion', models.CharField(db_column='nombre_situacion', max_length=50)),
                ('estado', models.IntegerField(db_column='estado', default=1)),
            ],
            options={
                'db_table': 'situacion_vehiculo',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='id_situacion',
            field=models.ForeignKey(blank=True, db_column='id_situacion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='software.situacionvehiculo'),
        ),
    ]
