# Generated by Django 5.2.6 on 2026-04-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0025_situacionvehiculo_vehiculo_id_situacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotasventa',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cuotasventa',
            name='interes_mora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='empresa',
            name='interes_mora_base',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Tasa de interés que se aplica a partir del 4to día de retraso', max_digits=5, verbose_name='Interés Mora Base (%)'),
        ),
    ]
