# Generated by Django 5.2.6 on 2026-05-01 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0026_remove_imposicionplaca_fecha_vencimiento_tramite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporteConductor',
            fields=[
                ('id_transporte_conductor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(db_column='nombre_completo', max_length=255)),
                ('dni', models.CharField(db_column='dni', max_length=15, unique=True)),
                ('licencia_conducir', models.CharField(db_column='licencia_conducir', max_length=20)),
                ('tipo_licencia', models.CharField(db_column='tipo_licencia', max_length=20)),
                ('telefono', models.CharField(blank=True, db_column='telefono', max_length=15, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_viaje', 'En Viaje'), ('descanso', 'En Descanso')], db_column='estado', default='disponible', max_length=20)),
            ],
            options={
                'db_table': 'transporte_conductor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransporteVehiculo',
            fields=[
                ('id_transporte_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(db_column='placa', max_length=20, unique=True)),
                ('marca', models.CharField(db_column='marca', max_length=50)),
                ('modelo', models.CharField(db_column='modelo', max_length=50)),
                ('tipo', models.CharField(choices=[('camion', 'Camión'), ('moto', 'Moto'), ('furgon', 'Furgón')], db_column='tipo', max_length=20)),
                ('capacidad', models.CharField(blank=True, db_column='capacidad', max_length=50, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_uso', 'En Uso'), ('mantenimiento', 'En Mantenimiento')], db_column='estado', default='disponible', max_length=20)),
            ],
            options={
                'db_table': 'transporte_vehiculo',
                'managed': True,
            },
        ),
        # migrations.RemoveField(
        #     model_name='imposicionplaca',
        #     name='fecha_vencimiento_tramite',
        # ),
        migrations.AddField(
            model_name='transferencia',
            name='tipo_transferencia',
            field=models.CharField(choices=[('sucursal_a_sucursal', 'Sucursal a Sucursal'), ('sucursal_a_exhibicion', 'Sucursal a Punto de Exhibición'), ('exhibicion_a_sucursal', 'Punto de Exhibición a Sucursal')], db_column='tipo_transferencia', default='sucursal_a_sucursal', max_length=30),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_transito', 'En Tránsito'), ('recibido', 'Recibido'), ('rechazada', 'Rechazada')], db_column='estado', default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='LogisticaTransferencia',
            fields=[
                ('id_logistica', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, db_column='fecha_asignacion')),
                ('fecha_salida', models.DateTimeField(blank=True, db_column='fecha_salida', null=True)),
                ('fecha_llegada_estimada', models.DateTimeField(blank=True, db_column='fecha_llegada_estimada', null=True)),
                ('estado_logistica', models.CharField(choices=[('activo', 'Activo'), ('sustituido', 'Sustituido'), ('completado', 'Completado')], db_column='estado_logistica', default='activo', max_length=20)),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True)),
                ('id_transferencia', models.ForeignKey(db_column='id_transferencia', on_delete=django.db.models.deletion.CASCADE, related_name='logisticas', to='software.transferencia')),
                ('id_transporte_conductor', models.ForeignKey(db_column='id_transporte_conductor', on_delete=django.db.models.deletion.RESTRICT, to='software.transporteconductor')),
                ('id_transporte_vehiculo', models.ForeignKey(db_column='id_transporte_vehiculo', on_delete=django.db.models.deletion.RESTRICT, to='software.transportevehiculo')),
            ],
            options={
                'db_table': 'logistica_transferencia',
                'managed': True,
            },
        ),
    ]
