# Generated by Django 5.2.6 on 2026-05-01 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0027_transporteconductor_transportevehiculo_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='imposicionplaca',
        #     name='fecha_vencimiento_tramite',
        # ),
        migrations.AddField(
            model_name='transferencia',
            name='direccion_destino',
            field=models.CharField(blank=True, db_column='direccion_destino', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='lugar_destino',
            field=models.CharField(blank=True, db_column='lugar_destino', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='idusuario_solicita',
            field=models.ForeignKey(db_column='idusuario_solicita', on_delete=django.db.models.deletion.DO_NOTHING, related_name='transferencias_solicitadas', to='software.usuario'),
        ),
    ]
