# Generated by Django 5.2.6 on 2026-05-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0029_remove_imposicionplaca_fecha_vencimiento_tramite_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='imposicionplaca',
        #     name='fecha_vencimiento_tramite',
        # ),
        migrations.AddField(
            model_name='transferencia',
            name='direccion_origen',
            field=models.CharField(blank=True, db_column='direccion_origen', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='lugar_origen',
            field=models.CharField(blank=True, db_column='lugar_origen', max_length=255, null=True),
        ),
    ]
