# Generated by Django 5.2.6 on 2026-05-01 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0030_remove_imposicionplaca_fecha_vencimiento_tramite_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='imposicionplaca',
        #     name='fecha_vencimiento_tramite',
        # ),
        migrations.AlterField(
            model_name='transferencia',
            name='id_almacen_origen',
            field=models.ForeignKey(blank=True, db_column='id_almacen_origen', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transferencias_salida', to='software.almacenes'),
        ),
    ]
