# Generated by Django 5.2.6 on 2026-05-03 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0031_remove_imposicionplaca_fecha_vencimiento_tramite_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='imposicionplaca',
        #     name='fecha_vencimiento_tramite',
        # ),
        migrations.AddField(
            model_name='cliente',
            name='id_distrito',
            field=models.ForeignKey(blank=True, db_column='iddistrito', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='software.distrito', verbose_name='Distrito'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_provincia',
            field=models.ForeignKey(blank=True, db_column='id_provincia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='software.provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_region',
            field=models.ForeignKey(blank=True, db_column='id_region', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='software.region', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='garante',
            name='id_distrito',
            field=models.ForeignKey(blank=True, db_column='iddistrito', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='software.distrito', verbose_name='Distrito'),
        ),
        migrations.AddField(
            model_name='garante',
            name='id_provincia',
            field=models.ForeignKey(blank=True, db_column='id_provincia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='software.provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='garante',
            name='id_region',
            field=models.ForeignKey(blank=True, db_column='id_region', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='software.region', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_transito', 'En Tránsito'), ('recibido', 'Recibido en Feria'), ('en_retorno', 'Retornando al Almacén'), ('completada', 'Completada / Recibida'), ('rechazada', 'Rechazada')], db_column='estado', default='pendiente', max_length=20),
        ),
    ]
