# Generated by Django 5.2.6 on 2026-05-03 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0032_remove_imposicionplaca_fecha_vencimiento_tramite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionVehicular',
            fields=[
                ('id_configuracion', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Configuración Vehicular',
                'verbose_name_plural': 'Configuraciones Vehiculares',
                'db_table': 'configuracion_vehicular',
                'managed': True,
            },
        ),
        # migrations.RemoveField(
        #     model_name='imposicionplaca',
        #     name='fecha_vencimiento_tramite',
        # ),
        migrations.AddField(
            model_name='vehiculo',
            name='id_configuracion',
            field=models.ForeignKey(blank=True, db_column='id_configuracion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='software.configuracionvehicular'),
        ),
    ]
