# Generated by Django 5.2.6 on 2026-05-03 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0033_configuracionvehicular_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='imposicionplaca',
        #     name='fecha_vencimiento_tramite',
        # ),
        migrations.AddField(
            model_name='producto',
            name='id_configuracion',
            field=models.ForeignKey(blank=True, db_column='id_configuracion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='software.configuracionvehicular'),
        ),
    ]
