# Generated by Django 5.2.6 on 2026-05-03 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0034_remove_imposicionplaca_fecha_vencimiento_tramite_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='imposicionplaca',
        #     name='fecha_vencimiento_tramite',
        # ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='id_configuracion',
        ),
    ]
