# Generated by Django 5.2.6 on 2026-05-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0035_remove_imposicionplaca_fecha_vencimiento_tramite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, help_text='Imagen del logo de la empresa', null=True, upload_to='logos/', verbose_name='Logo'),
        ),
    ]
