# Generated by Django 5.2.6 on 2026-05-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0036_logo_imagefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.CharField(blank=True, help_text='URL del logo en Cloudinary', max_length=500, null=True, verbose_name='Logo'),
        ),
    ]
