# Generated by Django 5.2.6 on 2026-05-07 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0037_logo_charfield_cloudinary_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaCredito',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'zonas_credito',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagen_perfil',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='FactorCredito',
            fields=[
                ('id_factor', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cuotas', models.IntegerField()),
                ('factor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('estado', models.IntegerField(default=1)),
                ('id_zona', models.ForeignKey(db_column='id_zona', on_delete=django.db.models.deletion.CASCADE, to='software.zonacredito')),
            ],
            options={
                'db_table': 'factores_credito',
                'managed': True,
            },
        ),
    ]
