# Generated by Django 5.2.6 on 2026-05-09 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0038_zonacredito_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compradetalle',
            old_name='precio_venta',
            new_name='precio_minimo',
        ),
    ]
