# Generated by Django 5.2.6 on 2026-05-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0039_auto_20260509_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='compradetalle',
            name='margen_maximo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='margen_minimo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='precio_maximo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
