# Generated by Django 5.2.6 on 2026-05-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0040_remove_imposicionplaca_fecha_vencimiento_tramite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalle',
            name='precio_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
