# Generated by Django 5.2.6 on 2026-05-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0041_remove_imposicionplaca_fecha_vencimiento_tramite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='margen_maximo_recuperacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='credito',
            name='margen_minimo_recuperacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
