# Generated by Django 5.2.6 on 2026-05-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0042_remove_imposicionplaca_fecha_vencimiento_tramite_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='empresa',
            name='dias_mora_inicio',
            field=models.IntegerField(default=4, help_text='Día en el que empieza a cobrarse el interés (ej: 4)', verbose_name='Día Inicio Mora'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='interes_mora_base',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Tasa de interés que se aplica a partir del día configurado', max_digits=5, verbose_name='Interés Mora Base (%)'),
        ),
    ]
