# Generated by Django 5.2.6 on 2026-05-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0043_remove_imposicionplaca_fecha_vencimiento_tramite_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='empresa',
            name='agradecimiento',
            field=models.TextField(blank=True, help_text='Mensaje de agradecimiento para los clientes', null=True, verbose_name='Agradecimiento'),
        ),
    ]
