# Generated by Django 5.2.6 on 2026-05-12 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0044_remove_imposicionplaca_fecha_vencimiento_tramite_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='empresa',
            name='direccion_gerente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección Gerente'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_distrito_gerente',
            field=models.ForeignKey(blank=True, db_column='id_distrito_gerente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='software.distrito', verbose_name='Distrito Gerente'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_provincia_gerente',
            field=models.ForeignKey(blank=True, db_column='id_provincia_gerente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='software.provincia', verbose_name='Provincia Gerente'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_region_gerente',
            field=models.ForeignKey(blank=True, db_column='id_region_gerente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='software.region', verbose_name='Departamento Gerente'),
        ),
    ]
