# Generated by Django 5.2.6 on 2026-05-13 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0045_remove_imposicionplaca_fecha_vencimiento_tramite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='conyuge_direccion',
        ),
    ]
