# Generated by Django 5.2.6 on 2026-05-14 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0046_remove_cliente_conyuge_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id_tipo_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Tipo de Cuenta')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tipo de Cuenta',
                'verbose_name_plural': 'Tipos de Cuenta',
                'db_table': 'tipo_cuenta',
                'managed': True,
            },
        ),

        migrations.CreateModel(
            name='CanalPago',
            fields=[
                ('id_canal', models.AutoField(primary_key=True, serialize=False)),
                ('banco', models.CharField(max_length=150, verbose_name='Banco')),
                ('numero_cuenta', models.CharField(max_length=50, verbose_name='Número de Cuenta')),
                ('cci', models.CharField(blank=True, max_length=50, null=True, verbose_name='CCI')),
                ('titular', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titular de la Cuenta')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_tipo_cuenta', models.ForeignKey(db_column='id_tipo_cuenta', on_delete=django.db.models.deletion.RESTRICT, to='software.tipocuenta', verbose_name='Tipo de Cuenta')),
            ],
            options={
                'verbose_name': 'Canal de Pago',
                'verbose_name_plural': 'Canales de Pago',
                'db_table': 'canales_pago',
                'ordering': ['orden', 'banco'],
                'managed': True,
            },
        ),
    ]
