# Generated by Django 5.2.6 on 2026-05-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0047_tipocuenta_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='canalpago',
            name='codigo_agente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Agente'),
        ),
    ]
