# Generated by Django 5.2.6 on 2026-05-14 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0048_remove_imposicionplaca_fecha_vencimiento_tramite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturacierrecaja',
            name='id_almacen',
            field=models.ForeignKey(blank=True, db_column='id_almacen', null=True, on_delete=django.db.models.deletion.SET_NULL, to='software.almacenes'),
        ),
    ]
