# Generated by Django 5.2.6 on 2026-05-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0049_apertura_caja_add_almacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='celular_gerente',
            field=models.CharField(blank=True, help_text='Número de celular del representante legal', max_length=20, null=True, verbose_name='Celular Gerente'),
        ),
    ]
