# Generated by Django 5.2.6 on 2026-05-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0051_remove_imposicionplaca_fecha_vencimiento_tramite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='gmail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
