# Generated by Django 5.2.6 on 2026-05-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0052_remove_imposicionplaca_fecha_vencimiento_tramite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imposicionplaca',
            name='fecha_vencimiento_tramite',
        ),
        migrations.AddField(
            model_name='empresa',
            name='ultramsg_instance',
            field=models.CharField(blank=True, help_text='ID de instancia de UltraMsg (ej: instance175698)', max_length=50, null=True, verbose_name='UltraMsg Instance ID'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ultramsg_token',
            field=models.CharField(blank=True, help_text='Token de autenticación de UltraMsg', max_length=100, null=True, verbose_name='UltraMsg Token'),
        ),
    ]
