# Generated by Django 5.2.6 on 2026-05-16 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0053_remove_imposicionplaca_fecha_vencimiento_tramite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorizacionAccion',
            fields=[
                ('idautorizacion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('tipo_accion', models.CharField(choices=[('EDICION', 'Edición'), ('ELIMINACION', 'Eliminación')], max_length=20)),
                ('modulo', models.CharField(max_length=100)),
                ('id_registro', models.IntegerField()),
                ('usado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('usuario_solicitante', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to='software.usuario')),
            ],
            options={
                'db_table': 'autorizacion_accion',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
