# Generated by Django 5.2.6 on 2026-05-16 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0054_autorizacionaccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'managed': True, 'ordering': ['nombrecomercial'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
    ]
