# Generated by Django 5.2.6 on 2026-05-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0055_alter_empresa_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizacionaccion',
            name='id_registro',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
