# Generated by Django 5.2.6 on 2026-05-26 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0056_alter_autorizacionaccion_id_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaBonificacion',
            fields=[
                ('id_regla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_producto', models.CharField(choices=[('Vehiculo', 'Vehculo'), ('Repuesto', 'Repuesto')], max_length=20)),
                ('tipo_comision', models.CharField(choices=[('Porcentaje', 'Porcentaje Directo (Vehculos)'), ('Escala', 'Escala por Volumen (Repuestos)')], max_length=20)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje para vehculos (ej. 1.50)', max_digits=5, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'regla_bonificacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CalculoBonificacion',
            fields=[
                ('id_calculo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio_periodo', models.DateField()),
                ('fecha_fin_periodo', models.DateField()),
                ('total_vehiculos_vendidos', models.IntegerField(default=0)),
                ('total_repuestos_vendidos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('porcentaje_cumplimiento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('comision_vehiculos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comision_repuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bono_meta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('Calculado', 'Calculado'), ('Observado', 'Observado'), ('Aprobado', 'Aprobado'), ('Pagado', 'Pagado'), ('Anulado', 'Anulado')], default='Calculado', max_length=20)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('vendedor', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to='software.usuario')),
            ],
            options={
                'db_table': 'calculo_bonificacion',
                'ordering': ['-fecha_inicio_periodo', '-fecha_calculo'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MetaVendedor',
            fields=[
                ('id_meta', models.AutoField(primary_key=True, serialize=False)),
                ('mes_anio', models.DateField(help_text='Primer da del mes de la meta')),
                ('meta_soles', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('meta_unidades', models.IntegerField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('Vehiculos', 'Vehculos'), ('Repuestos', 'Repuestos'), ('Ambas', 'Ambas')], max_length=20)),
                ('vendedor', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to='software.usuario')),
            ],
            options={
                'db_table': 'meta_vendedor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RangoBonificacion',
            fields=[
                ('id_rango', models.AutoField(primary_key=True, serialize=False)),
                ('monto_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rangos', to='software.reglabonificacion')),
            ],
            options={
                'db_table': 'rango_bonificacion',
                'ordering': ['monto_minimo'],
                'managed': True,
            },
        ),
    ]
