# Generated by Django 5.2.6 on 2026-05-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0057_reglabonificacion_calculobonificacion_metavendedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metavendedor',
            name='porcentaje_bono',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje adicional de la comisión base si se cumple la meta', max_digits=5),
        ),
    ]
