# Generated by Django 5.2.6 on 2026-05-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0058_metavendedor_porcentaje_bono'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='gmail_1',
            field=models.EmailField(blank=True, help_text='Primer correo electrónico de la empresa', max_length=255, null=True, verbose_name='Gmail 1'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='gmail_2',
            field=models.EmailField(blank=True, help_text='Segundo correo electrónico de la empresa', max_length=255, null=True, verbose_name='Gmail 2'),
        ),
    ]
