# Generated by Django 5.2.6 on 2026-05-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0059_empresa_gmail_1_empresa_gmail_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo_ticket',
            field=models.CharField(blank=True, help_text='URL del logo para tickets en Cloudinary', max_length=500, null=True, verbose_name='Logo Ticket'),
        ),
    ]
