# Generated by Django 5.2.6 on 2026-06-04 19:16
# Modificado manualmente:
# - ventas.fecha_venta: el índice ya existe en producción → SeparateDatabaseAndState
#   para que Django registre el campo como db_index=True sin intentar crear el índice.
# - El resto de índices se crean normalmente vía AlterField.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0060_empresa_logo_ticket'),
    ]

    operations = [
        # ── Credito ──
        migrations.AlterField(
            model_name='credito',
            name='estado',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='credito',
            name='estado_credito',
            field=models.CharField(db_index=True, default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='credito',
            name='fecha_credito',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        # ── CuotasVenta ──
        migrations.AlterField(
            model_name='cuotasventa',
            name='estado',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='cuotasventa',
            name='estado_pago',
            field=models.CharField(db_index=True, default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuotasventa',
            name='fecha_vencimiento',
            field=models.DateField(db_index=True),
        ),
        # ── Ventas.estado ──
        migrations.AlterField(
            model_name='ventas',
            name='estado',
            field=models.IntegerField(db_index=True, default=1),
        ),
        # ── Ventas.fecha_venta ──
        # El índice ya existe en la BD de producción (ventas_fecha_venta_fd6faed7).
        # Usamos SeparateDatabaseAndState para que Django actualice su estado
        # interno sin intentar crear el índice duplicado.
        migrations.SeparateDatabaseAndState(
            database_operations=[],   # No tocar la BD (índice ya existe)
            state_operations=[
                migrations.AlterField(
                    model_name='ventas',
                    name='fecha_venta',
                    field=models.DateTimeField(auto_now_add=True, db_index=True),
                ),
            ],
        ),
    ]
