# Generated by Django 5.2.6 on 2026-06-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0061_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocuota',
            name='estado',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='pagocuota',
            name='fecha_pago',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='estado',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='tipo_item',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
