# Generated by Django 5.2.6 on 2026-06-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0062_alter_pagocuota_estado_alter_pagocuota_fecha_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Teléfono'),
        ),
    ]
