# Generated by Django 5.2.6 on 2026-06-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0064_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Teléfono'),
        ),
    ]
