# Generated by Django 5.2.6 on 2026-06-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0065_alter_proveedor_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='igv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
