# Generated by Django 5.2.6 on 2026-06-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0066_ventas_igv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono de contacto', max_length=40, null=True, verbose_name='Teléfono'),
        ),
    ]
