# Generated by Django 5.2.6 on 2026-06-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0067_alter_empresa_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='numcorrelativo',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
