# Generated by Django 5.2.6 on 2026-06-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0068_alter_compras_numcorrelativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='garante',
            name='conyuge_dni',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI del Cónyuge'),
        ),
        migrations.AddField(
            model_name='garante',
            name='conyuge_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Cónyuge'),
        ),
    ]
