# Generated by Django 5.2.6 on 2026-06-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0069_garante_conyuge_dni_garante_conyuge_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
