# Generated by Django 5.2.6 on 2026-06-29 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0070_add_observaciones_to_compras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(db_column='id_servicio', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=255, verbose_name='Nombre del Servicio')),
                ('precio_defecto', models.DecimalField(db_column='precio_defecto', decimal_places=2, max_digits=10, verbose_name='Precio Base')),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True, verbose_name='Descripción')),
                ('estado', models.IntegerField(db_column='estado', default=1)),
            ],
            options={
                'verbose_name': 'Servicio / Trámite',
                'verbose_name_plural': 'Servicios / Trámites',
                'db_table': 'servicios_tramites',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='id_servicio',
            field=models.ForeignKey(blank=True, db_column='id_servicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='software.servicio'),
        ),
    ]
