# Generated by Django 5.2.6 on 2026-06-29 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0071_add_servicios_tramites'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='repuestocomp',
        #     name='modelo',
        # ),
        migrations.AddField(
            model_name='repuesto',
            name='idmodelo',
            field=models.ForeignKey(blank=True, db_column='idmodelo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='repuestos', to='software.modelo'),
        ),
    ]
