# Generated by Django 5.2.6 on 2026-07-04 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0072_remove_repuestocomp_modelo_repuesto_idmodelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleColor',
            fields=[
                ('iddetalle_color', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_color',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='id_detalle_color',
            field=models.ForeignKey(blank=True, db_column='id_detalle_color', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='software.detallecolor'),
        ),
    ]
