# Generated by Django 5.2.6 on 2026-07-05 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0073_detalle_color_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRepuesto',
            fields=[
                ('idcategoria_repuesto', models.AutoField(db_column='idcategoria_repuesto', primary_key=True, serialize=False)),
                ('nomcategoria', models.CharField(db_column='nomcategoria', max_length=255, verbose_name='Nombre Categoria')),
                ('estado', models.IntegerField(db_column='estado', default=1)),
            ],
            options={
                'db_table': 'categoria_repuesto',
                'ordering': ['nomcategoria'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MarcaRepuesto',
            fields=[
                ('idmarca_repuesto', models.AutoField(db_column='idmarca_repuesto', primary_key=True, serialize=False)),
                ('nombremarca', models.CharField(db_column='nombremarca', max_length=100, verbose_name='Nombre Marca')),
                ('estado', models.IntegerField(db_column='estado', default=1)),
            ],
            options={
                'db_table': 'marca_repuesto',
                'ordering': ['nombremarca'],
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='idcolor',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='idmodelo',
        ),
        migrations.AddField(
            model_name='repuesto',
            name='codigo_barras',
            field=models.CharField(blank=True, db_column='codigo_barras', max_length=100, null=True, verbose_name='Codigo de Barras'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='costo_unitario',
            field=models.DecimalField(db_column='costo_unitario', decimal_places=2, default=0, max_digits=10, verbose_name='Costo Unitario'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='descripcion',
            field=models.TextField(blank=True, db_column='descripcion', null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='garantia',
            field=models.CharField(blank=True, db_column='garantia', max_length=50, null=True, verbose_name='Garantia'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='modelo_referencia',
            field=models.CharField(blank=True, db_column='modelo_referencia', max_length=100, null=True, verbose_name='Modelo/Referencia'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='observaciones',
            field=models.TextField(blank=True, db_column='observaciones', null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='precio_minimo',
            field=models.DecimalField(db_column='precio_minimo', decimal_places=2, default=0, max_digits=10, verbose_name='Precio Minimo'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='precio_sugerido',
            field=models.DecimalField(db_column='precio_sugerido', decimal_places=2, default=0, max_digits=10, verbose_name='Precio Sugerido'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='stock_maximo',
            field=models.IntegerField(db_column='stock_maximo', default=0, verbose_name='Stock Maximo'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='stock_minimo',
            field=models.IntegerField(db_column='stock_minimo', default=0, verbose_name='Stock Minimo'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='codigo_interno',
            field=models.CharField(blank=True, db_column='codigo_interno', max_length=50, null=True, verbose_name='Codigo Interno'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='estado',
            field=models.IntegerField(db_column='estado', default=1),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='id_categoria_repuesto',
            field=models.ForeignKey(blank=True, db_column='id_categoria_repuesto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='repuestos', to='software.categoriarepuesto'),
        ),
        # Paso 1: Quitar la restriccion NOT NULL de idmarca en la BD
        # (la columna fue definida como NOT NULL en la tabla original)
        migrations.RunSQL(
            sql="ALTER TABLE repuestos ALTER COLUMN idmarca DROP NOT NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Paso 2: Limpiar idmarca existente antes de cambiar la FK a la nueva tabla marca_repuesto
        # Los repuestos existentes apuntaban a la tabla 'marca' de vehiculos; al migrar
        # a la nueva tabla 'marca_repuesto' (que estara vacia), debemos poner idmarca=NULL
        # para evitar violaciones de FK. El usuario registrara las marcas nuevamente.
        migrations.RunSQL(
            sql="UPDATE repuestos SET idmarca = NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='idmarca',
            field=models.ForeignKey(blank=True, db_column='idmarca', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='repuestos', to='software.marcarepuesto'),
        ),
    ]
