# Generated by Django 5.2.6 on 2026-07-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0074_categoriarepuesto_marcarepuesto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repuestocomp',
            old_name='descripcion',
            new_name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='repuestocomp',
            name='codigo_barras',
        ),
    ]
