# Generated by Django 5.2.6 on 2026-07-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0075_rename_descripcion_repuestocomp_ubicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='compatibilidad',
            field=models.TextField(blank=True, db_column='compatibilidad', null=True, verbose_name='Compatibilidad'),
        ),
    ]
