# Generated by Django 5.2.6 on 2026-07-07 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0076_remove_repuestocomp_modelo_repuesto_compatibilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarantiaRepuesto',
            fields=[
                ('id_garantia_repuesto', models.AutoField(db_column='id_garantia_repuesto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=255)),
                ('estado', models.IntegerField(db_column='estado', default=1)),
            ],
            options={
                'db_table': 'garantia_repuesto',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='garantia',
        ),
        migrations.AddField(
            model_name='repuesto',
            name='id_garantia_repuesto',
            field=models.ForeignKey(blank=True, db_column='id_garantia_repuesto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='repuestos', to='software.garantiarepuesto', verbose_name='Garantia'),
        ),
    ]
