# Generated by Django 5.2.6 on 2026-07-15 02:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0077_garantiarepuesto_remove_repuesto_garantia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='fecha_venta',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
