# Generated by Django 5.2.6 on 2026-07-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0078_remove_repuestocomp_modelo_alter_ventas_fecha_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='codigo_barras',
            field=models.CharField(blank=True, db_column='codigo_barras', db_index=True, max_length=100, null=True, verbose_name='Codigo de Barras'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='serie_chasis',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='serie_motor',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
