# Generated by Django 5.2.6 on 2026-07-15 11:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0079_remove_repuestocomp_modelo_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='credito',
            name='fecha_credito',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
