# Generated by Django 5.2.6 on 2026-07-15 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0080_remove_repuestocomp_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocuota',
            name='fecha_pago',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
