# Generated by Django 5.2.6 on 2026-07-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0081_alter_pagocuota_fecha_pago'),
    ]

    operations = [

        migrations.AddField(
            model_name='imposicionplaca',
            name='con_garantia_mobiliaria',
            field=models.BooleanField(default=False),
        ),
    ]
