# Generated by Django 5.2.6 on 2026-07-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0082_remove_repuestocomp_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='estado',
            field=models.IntegerField(db_column='estado', db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='fecha_movimiento',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_movimiento', db_index=True),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], db_column='tipo_movimiento', db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['fecha_movimiento', 'tipo_movimiento'], name='idx_caja_fecha_tipo'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['id_caja', 'fecha_movimiento'], name='idx_caja_id_fecha'),
        ),
        migrations.AddIndex(
            model_name='pagocuota',
            index=models.Index(fields=['id_movimiento_caja', 'estado'], name='idx_pagocuota_mov_estado'),
        ),
        migrations.AddIndex(
            model_name='pagocuota',
            index=models.Index(fields=['idcuotaventa', 'estado'], name='idx_pagocuota_cuota_estado'),
        ),
    ]
