# Generated by Django 5.2.6 on 2026-07-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0083_add_indexes_movimientocaja_pagocuota'),
    ]

    operations = [

        migrations.AddField(
            model_name='empresa',
            name='cobrar_mora',
            field=models.BooleanField(default=True, help_text='Activa o desactiva el cobro de mora en todos los créditos', verbose_name='Cobrar Mora'),
        ),
    ]
