# Generated by Django 5.2.6 on 2026-07-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0084_remove_repuestocomp_modelo_empresa_cobrar_mora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repuestocomp',
            name='modelo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='puede_gestionar_logistica',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
