# Generated by Django 5.2.6 on 2026-07-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0085_remove_repuestocomp_modelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='precredito',
            name='cobrado',
            field=models.BooleanField(default=False, verbose_name='Cobrado'),
        ),
        migrations.AddField(
            model_name='precredito',
            name='observacion_evaluacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación de Evaluación'),
        ),
    ]
