# Generated by Django 5.2.6 on 2026-07-25 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0086_precredito_cobrado_precredito_observacion_evaluacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='id_sucursal',
            field=models.ForeignKey(blank=True, db_column='id_sucursal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='software.sucursales'),
        ),
    ]
