# Generated by Django 5.2.6 on 2026-07-25 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0087_alter_caja_id_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='id_empresa',
            field=models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='software.empresa'),
        ),
    ]
