# Generated by Django 5.2.6 on 2026-07-26 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0088_caja_id_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreCreditoDetalleVehiculo',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('id_pre_credito', models.ForeignKey(db_column='id_pre_credito', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_vehiculos', to='software.precredito', verbose_name='Pre-Crédito')),
                ('id_vehiculo', models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_precreditos', to='software.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Detalle de Vehículo de Pre-Crédito',
                'verbose_name_plural': 'Detalles de Vehículos de Pre-Crédito',
                'db_table': 'pre_credito_detalle_vehiculo',
                'managed': True,
                'indexes': [models.Index(fields=['id_pre_credito'], name='pre_credito_id_pre__7bdf81_idx'), models.Index(fields=['id_vehiculo'], name='pre_credito_id_vehi_efefc0_idx')],
            },
        ),
    ]
