# Generated by Django 5.2.6 on 2026-07-26 13:53

from django.db import migrations

def migrate_vehiculos(apps, schema_editor):
    PreCredito = apps.get_model('software', 'PreCredito')
    PreCreditoDetalleVehiculo = apps.get_model('software', 'PreCreditoDetalleVehiculo')

    detalles_to_create = []
    # Usar .iterator() para no cargar todo en memoria si son muchos
    for pre_credito in PreCredito.objects.filter(id_vehiculo__isnull=False).iterator():
        detalles_to_create.append(
            PreCreditoDetalleVehiculo(
                id_pre_credito=pre_credito,
                id_vehiculo=pre_credito.id_vehiculo
            )
        )
    
    # Hacer bulk_create en lotes de 1000 para eficiencia
    if detalles_to_create:
        PreCreditoDetalleVehiculo.objects.bulk_create(detalles_to_create, batch_size=1000)

def reverse_migrate_vehiculos(apps, schema_editor):
    pass # No rellenamos el id_vehiculo al revertir, pues id_vehiculo será eliminado más adelante.

class Migration(migrations.Migration):

    dependencies = [
        ('software', '0089_precreditodetallevehiculo'),
    ]

    operations = [
        migrations.RunPython(migrate_vehiculos, reverse_migrate_vehiculos),
    ]
