# Generated by Django 5.2.6 on 2026-07-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0090_migrate_precredito_vehiculos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precredito',
            name='id_vehiculo',
        ),
    ]
