# Generated by Django 5.2.6 on 2026-07-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0091_remove_precredito_id_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='estado_cobro',
            field=models.CharField(db_index=True, default='Pagado', max_length=20),
        ),
    ]
