# Generated by Django 5.2.6 on 2026-07-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0092_ventas_estado_cobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='compradetalle',
            name='moneda',
            field=models.CharField(blank=True, default='PEN', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='precio_dolares',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='compras',
            name='tipo_cambio',
            field=models.DecimalField(blank=True, decimal_places=4, default=1.0, max_digits=10, null=True),
        ),
    ]
