# Generated by Django 5.2.6 on 2026-07-29 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0093_compradetalle_moneda_compradetalle_precio_dolares_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='es_credito',
            field=models.BooleanField(default=False, verbose_name='Es al Crédito'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='factor_aplicado',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Factor Aplicado'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='interes_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Interés Total'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='monto_cuota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto por Cuota'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='monto_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Inicial'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='numero_cuotas',
            field=models.IntegerField(default=0, verbose_name='Número de Cuotas'),
        ),
    ]
