# Generated by Django 5.2.6 on 2026-07-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0094_proforma_es_credito_proforma_factor_aplicado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='tipo_periodo',
            field=models.CharField(default='meses', max_length=50, verbose_name='Tipo de Periodo'),
        ),
    ]
