# Generated by Django 5.2.6 on 2026-08-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0095_proforma_tipo_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='condiciones_comerciales',
            field=models.TextField(blank=True, default='Precios sujetos a cambios sin previo aviso según fluctuación del dólar.', help_text='Condiciones comerciales por defecto para las proformas', null=True, verbose_name='Condiciones Comerciales'),
        ),
    ]
