# Generated by Django 5.2.6 on 2026-08-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0096_empresa_condiciones_comerciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='compradetalle',
            name='margen_por_mayor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='precio_por_mayor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='precio_por_mayor',
            field=models.DecimalField(db_column='precio_por_mayor', decimal_places=2, default=0, max_digits=10, verbose_name='Precio por Mayor'),
        ),
    ]
