# Generated by Django 5.2.6 on 2026-08-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0097_compradetalle_margen_por_mayor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reglabonificacion',
            name='porcentaje',
        ),
        migrations.AddField(
            model_name='reglabonificacion',
            name='porcentaje_cash',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje para Precio Cash (ej. 1.50)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='reglabonificacion',
            name='porcentaje_lista',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje para Precio Lista (ej. 2.00)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='reglabonificacion',
            name='porcentaje_mayor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje para Precio Mayor (ej. 1.00)', max_digits=5, null=True),
        ),
    ]
