# Generated by Django 5.2.6 on 2026-08-06 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0098_remove_reglabonificacion_porcentaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriecomprobante',
            name='id_sucursal',
            field=models.ForeignKey(blank=True, db_column='id_sucursal', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series_comprobante', to='software.sucursales', verbose_name='Sucursal'),
        ),
    ]
