# Generated by Django 5.2.6 on 2026-08-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0099_seriecomprobante_id_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='limite_dias_amarillo',
            field=models.IntegerField(default=20, help_text='Hasta cuántos días de mora se muestra el color amarillo (mayor a esto será rojo)', verbose_name='Límite Días Amarillo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='limite_dias_verde',
            field=models.IntegerField(default=10, help_text='Hasta cuántos días de mora se muestra el color verde', verbose_name='Límite Días Verde'),
        ),
    ]
