# Generated by Django 5.2.6 on 2026-08-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0100_empresa_limite_dias_amarillo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
