# Generated by Django 5.2.6 on 2026-08-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0101_cliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='frecuencia_pago',
            field=models.CharField(db_index=True, default='Personalizado', max_length=20),
        ),
    ]
