# Generated by Django 5.2.6 on 2026-08-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0102_credito_frecuencia_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='limite_cuotas_amarillo_mensual',
            field=models.IntegerField(default=2, help_text='Número de cuotas vencidas para color amarillo en créditos mensuales (más es rojo)', verbose_name='Límite Amarillo (Mensual - Cuotas)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='limite_cuotas_verde_mensual',
            field=models.IntegerField(default=1, help_text='Número de cuotas vencidas para color verde en créditos mensuales', verbose_name='Límite Verde (Mensual - Cuotas)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='limite_dias_amarillo_diario',
            field=models.IntegerField(default=10, help_text='Días de mora para color amarillo en créditos diarios (más es rojo)', verbose_name='Límite Amarillo (Diario)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='limite_dias_amarillo_quincenal',
            field=models.IntegerField(default=45, help_text='Días de mora para color amarillo en créditos quincenales (más es rojo)', verbose_name='Límite Amarillo (Quincenal)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='limite_dias_amarillo_semanal',
            field=models.IntegerField(default=30, help_text='Días de mora para color amarillo en créditos semanales (más es rojo)', verbose_name='Límite Amarillo (Semanal)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='limite_dias_verde_diario',
            field=models.IntegerField(default=5, help_text='Días de mora para color verde en créditos diarios', verbose_name='Límite Verde (Diario)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='limite_dias_verde_quincenal',
            field=models.IntegerField(default=30, help_text='Días de mora para color verde en créditos quincenales', verbose_name='Límite Verde (Quincenal)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='limite_dias_verde_semanal',
            field=models.IntegerField(default=20, help_text='Días de mora para color verde en créditos semanales', verbose_name='Límite Verde (Semanal)'),
        ),
    ]
