# Generated by Django 5.2.6 on 2026-08-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0103_empresa_limites_mora_por_frecuencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturacierrecaja',
            name='saldo_final_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aperturacierrecaja',
            name='saldo_inicial_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='moneda',
            field=models.CharField(db_column='moneda', default='PEN', max_length=3),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='monto_base_soles',
            field=models.DecimalField(blank=True, db_column='monto_base_soles', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='tipo_cambio_aplicado',
            field=models.DecimalField(db_column='tipo_cambio_aplicado', decimal_places=4, default=1.0, max_digits=10),
        ),
    ]
