# Generated by Django 5.2.6 on 2026-08-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0104_aperturacierrecaja_saldo_final_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacenes',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
