# Generated by Django 5.2.6 on 2026-08-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0105_almacenes_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='moneda',
            field=models.CharField(blank=True, db_column='moneda', default='PEN', max_length=3, null=True),
        ),
    ]
