# Generated by Django 5.2.6 on 2026-08-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0106_ventas_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='sunat_cdr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
