# Generated by Django 5.2.6 on 2026-08-16 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0107_add_sunat_cdr_to_ventas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaCajas',
            fields=[
                ('idauditoria_caja', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=50)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('fecha_auditoria', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id_caja', models.ForeignKey(blank=True, db_column='id_caja', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='auditorias_caja', to='software.caja')),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='auditorias_cajas', to='software.usuario')),
            ],
            options={
                'verbose_name': 'Auditoría de Caja',
                'verbose_name_plural': 'Auditorías de Cajas',
                'db_table': 'auditoria_cajas',
                'ordering': ['-fecha_auditoria'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AuditoriaCreditos',
            fields=[
                ('idauditoria_credito', models.AutoField(primary_key=True, serialize=False)),
                ('idcredito', models.IntegerField(db_index=True)),
                ('accion', models.CharField(max_length=50)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('fecha_auditoria', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='auditorias_creditos', to='software.usuario')),
            ],
            options={
                'verbose_name': 'Auditoría de Crédito',
                'verbose_name_plural': 'Auditorías de Créditos',
                'db_table': 'auditoria_creditos',
                'ordering': ['-fecha_auditoria'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AuditoriaProductos',
            fields=[
                ('idauditoria_producto', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=50)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('fecha_auditoria', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('idproducto', models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='auditorias_producto', to='software.producto')),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='auditorias_productos', to='software.usuario')),
            ],
            options={
                'verbose_name': 'Auditoría de Producto',
                'verbose_name_plural': 'Auditorías de Productos',
                'db_table': 'auditoria_productos',
                'ordering': ['-fecha_auditoria'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AuditoriaUsuarios',
            fields=[
                ('idauditoria_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=50)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('fecha_auditoria', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario_afectado', models.ForeignKey(db_column='usuario_afectado', on_delete=django.db.models.deletion.DO_NOTHING, related_name='auditorias_afectado', to='software.usuario')),
                ('usuario_responsable', models.ForeignKey(blank=True, db_column='usuario_responsable', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='auditorias_responsable', to='software.usuario')),
            ],
            options={
                'verbose_name': 'Auditoría de Usuario',
                'verbose_name_plural': 'Auditorías de Usuarios',
                'db_table': 'auditoria_usuarios',
                'ordering': ['-fecha_auditoria'],
                'managed': True,
            },
        ),
    ]
